### ISSUE TITLE
Review 1 "Throw Errors"

### ISSUE THREAD

**Issue by leonhaufe** [moritz155/ParallelPlots#15]
# Throw errors
* errors should be thrown
-- on empty datasets
-- on datasets containing null values
-- on datasets containing non number values
-- datasets containing only one feature --> Division by zero in get in ParallelPlots.jl ln. 80
-- datasets containing only one sample --> Division by zero in get in ParallelPlots.jl ln. 106

### Linked to #8 "Throw Errors"

**Comment by moritz155** [comment]
closed by PR https://github.com/moritz155/ParallelPlots/pull/18
